# Generated by Django 4.2.7 on 2026-02-13 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief ticket title', max_length=500)),
                ('description', models.TextField(help_text='Detailed ticket description')),
                ('predicted_category', models.CharField(blank=True, help_text='Category predicted by ML model', max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Prediction confidence (0-1)', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, help_text="Reporter's email", max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_text', models.TextField(help_text='AI-generated resolution')),
                ('method', models.CharField(help_text="Method used: 'llm', 'rule_based', 'similar_tickets'", max_length=50)),
                ('similar_tickets_count', models.IntegerField(default=0, help_text='Number of similar tickets found')),
                ('is_helpful', models.BooleanField(blank=True, help_text='User feedback on resolution quality', null=True)),
                ('feedback_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcategory'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SimilarTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_ticket_id', models.IntegerField(help_text='ID from historical dataset')),
                ('similarity_score', models.FloatField(help_text='Cosine similarity (0-1)')),
                ('similar_title', models.CharField(max_length=500)),
                ('similar_description', models.TextField()),
                ('similar_category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-created_at'], name='tickets_tic_created_c2132d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['predicted_category'], name='tickets_tic_predict_a9ff05_idx'),
        ),
    ]
