"""
Django Models for ITSM Tickets

This file defines the database schema for:
- Ticket: Main ticket model with all fields
- TicketCategory: Predefined categories
- TicketResolution: AI-generated resolutions
"""

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class TicketCategory(models.Model):
    """
    Predefined ticket categories learned from ML model
    """
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Ticket Categories"
        ordering = ['name']
    
    def __str__(self):
        return self.name


class Ticket(models.Model):
    """
    Main Ticket Model
    
    Represents an IT service ticket with all information needed
    for classification and resolution.
    """
    
    # Status choices
    STATUS_CHOICES = [
        ('open', 'Open'),
        ('in_progress', 'In Progress'),
        ('resolved', 'Resolved'),
        ('closed', 'Closed'),
    ]
    
    # Priority choices
    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    ]
    
    # Basic Information
    title = models.CharField(max_length=500, help_text="Brief ticket title")
    description = models.TextField(help_text="Detailed ticket description")
    
    # Classification (AI-predicted)
    predicted_category = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        help_text="Category predicted by ML model"
    )
    confidence_score = models.FloatField(
        blank=True,
        null=True,
        help_text="Prediction confidence (0-1)"
    )
    
    # Manual category override
    category = models.ForeignKey(
        TicketCategory,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='tickets'
    )
    
    # Priority and Status
    priority = models.CharField(
        max_length=20,
        choices=PRIORITY_CHOICES,
        default='medium'
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='open'
    )
    
    # Assignment
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_tickets'
    )
    assigned_to = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='assigned_tickets'
    )
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    
    # Additional metadata
    email = models.EmailField(blank=True, help_text="Reporter's email")
    phone = models.CharField(max_length=20, blank=True)
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['-created_at']),
            models.Index(fields=['status']),
            models.Index(fields=['predicted_category']),
        ]
    
    def __str__(self):
        return f"[{self.status.upper()}] {self.title[:50]}"
    
    def save(self, *args, **kwargs):
        # Auto-set resolved_at when status changes to resolved
        if self.status == 'resolved' and not self.resolved_at:
            self.resolved_at = timezone.now()
        super().save(*args, **kwargs)


class TicketResolution(models.Model):
    """
    AI-Generated Resolutions for Tickets
    
    Stores resolutions generated by the RAG system
    """
    ticket = models.ForeignKey(
        Ticket,
        on_delete=models.CASCADE,
        related_name='resolutions'
    )
    
    # Resolution content
    resolution_text = models.TextField(help_text="AI-generated resolution")
    method = models.CharField(
        max_length=50,
        help_text="Method used: 'llm', 'rule_based', 'similar_tickets'"
    )
    
    # Similar tickets used for RAG
    similar_tickets_count = models.IntegerField(
        default=0,
        help_text="Number of similar tickets found"
    )
    
    # Feedback
    is_helpful = models.BooleanField(
        null=True,
        blank=True,
        help_text="User feedback on resolution quality"
    )
    feedback_notes = models.TextField(blank=True)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"Resolution for: {self.ticket.title[:30]}"


class SimilarTicket(models.Model):
    """
    Stores similar ticket relationships found by semantic search
    """
    ticket = models.ForeignKey(
        Ticket,
        on_delete=models.CASCADE,
        related_name='similar_to'
    )
    similar_ticket_id = models.IntegerField(help_text="ID from historical dataset")
    similarity_score = models.FloatField(help_text="Cosine similarity (0-1)")
    similar_title = models.CharField(max_length=500)
    similar_description = models.TextField()
    similar_category = models.CharField(max_length=100)
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-similarity_score']
    
    def __str__(self):
        return f"Similar to {self.ticket.id}: {self.similarity_score:.2f}"
